'use strict';
//  ============================================================
//  lab/inline.js — the Neural Core, copied into index.html  (D1)
//  ============================================================
//
//  lab/ is the only source of the boss's brain. index.html carries a
//  generated copy between two marker lines, so the game still opens as one
//  file with no build step, and nothing is ever edited in two places:
//
//    node lab/inline.js          rewrite the block in index.html
//    node lab/inline.js --check  exit 1 if the block is out of date (tests use this)
//
//  What goes in: the modules the game runs (not the compressor, the lab, or
//  the tests), each wrapped so its require() finds the others, and the
//  connectome already built and compressed — building it in the browser
//  costs a stall D8 does not allow (see packGraph in connectome.js).

const fs = require('fs');
const path = require('path');
const { buildMockConnectome, packGraph } = require('./core/connectome.js');
const C = require('./core/compress.js');

const ROOT = path.resolve(__dirname, '..');
const INDEX = path.join(ROOT, 'index.html');
const BEGIN = '  // ==== NEURAL CORE — generated by lab/inline.js from lab/; edit there and re-run, never here ====';
const END = '  // ==== END NEURAL CORE ====';
const ANCHOR = '  // @@NEURAL_CORE@@';

//  The graph the boss thinks with. Changing these is changing its brain:
//  the Phase 2 bench chose 500 nodes, compressed from 2000, as the size that
//  discriminates situations and still costs well under a millisecond a tick.
const GRAPH = { nodes: 2000, seed: 0x5eed, keep: 500 };

const MODULES = [
  ['rng.js', 'core/rng.js'],
  ['connectome.js', 'core/connectome.js'],
  ['neural.js', 'core/neural.js'],
  ['worldstate.js', 'core/worldstate.js'],
  ['sensors.js', 'core/sensors.js'],
  ['fairness.js', 'core/fairness.js'],
  ['memory.js', 'core/memory.js'],
  ['player_model.js', 'core/player_model.js'],
  ['boss_body.js', 'core/boss_body.js'],
  ['tactics.js', 'core/tactics.js'],
  ['fsm_brain.js', 'core/fsm_brain.js'],
  ['game_adapter.js', 'adapter/game_adapter.js'],
];

function block() {
  const g = C.hybrid(buildMockConnectome({ nodes: GRAPH.nodes, seed: GRAPH.seed }), GRAPH.keep);
  const packed = packGraph(g);
  const parts = [BEGIN,
    '  //  ' + MODULES.map((m) => m[1]).join(', '),
    '  //  graph: mock connectome, ' + GRAPH.nodes + ' nodes compressed to ' + g.n + ' (' + g.m + ' edges), fingerprint ' + g.fingerprint(),
    '  const NC = (function () {',
    '    const defs = {'];
  for (const [name, rel] of MODULES) {
    const src = fs.readFileSync(path.join(__dirname, rel), 'utf8').replace(/\r\n/g, '\n');
    parts.push('      ' + JSON.stringify(name) + ': function (module, exports, require) {   // lab/' + rel);
    //  The commentary lives in lab/, where it is read; the copy drops lines
    //  that are only comments, and blank runs, which roughly halves it.
    //  Indented for reading — unless a line opens a template literal it does
    //  not close, where touching lines would change the string's contents.
    const lines = src.split('\n');
    const multiline = lines.some((l) => { const code = l.replace(/\/\/.*$/, '').replace(/'(?:[^'\\]|\\.)*'/g, ''); return (code.split('`').length - 1) % 2 === 1; });
    if (multiline) parts.push(src);
    else {
      const kept = [];
      for (const l of lines) {
        const t = l.trim();
        if (t.startsWith('//')) continue;
        if (!t && (!kept.length || !kept[kept.length - 1])) continue;
        kept.push(t ? '        ' + l : '');
      }
      parts.push(kept.join('\n'));
    }
    parts.push('      },');
  }
  parts.push('    };',
    '    const cache = {};',
    '    function req(name) {',
    "      name = name.replace(/^.*\\//, '');",
    '      if (cache[name]) return cache[name].exports;',
    '      const m = { exports: {} }; cache[name] = m;',
    '      defs[name](m, m.exports, req);',
    '      return m.exports;',
    '    }',
    '    return req;',
    '  })();',
    '  const NC_GRAPH = ' + JSON.stringify(packed) + ';',
    END);
  return parts.join('\n');
}

function current(html) {
  const a = html.indexOf(BEGIN), b = html.indexOf(END);
  if (a < 0 || b < 0) return null;
  return html.slice(a, b + END.length);
}

if (require.main === module) {
  const html = fs.readFileSync(INDEX, 'utf8');
  const want = block();
  const have = current(html);
  if (process.argv.includes('--check')) {
    if (have === want) { console.log('lab/inline.js: index.html is up to date'); process.exit(0); }
    console.error('lab/inline.js: the Neural Core block in index.html is ' + (have ? 'out of date' : 'missing') + ' — run node lab/inline.js');
    process.exit(1);
  }
  let out;
  // a function, so a '$' anywhere in the code is never read as a replacement pattern
  if (have !== null) out = html.replace(have, () => want);
  else if (html.includes(ANCHOR)) out = html.replace(ANCHOR, () => want);
  else { console.error('lab/inline.js: no block and no ' + ANCHOR.trim() + ' anchor in index.html'); process.exit(1); }
  fs.writeFileSync(INDEX, out);
  console.log('lab/inline.js: wrote ' + (want.length / 1024).toFixed(0) + ' KB into index.html');
}

module.exports = { block, current, BEGIN, END, ANCHOR };
