'use strict';
//  ============================================================
//  lab/inline.js — the Neural Core, copied into index.html  (D1)
//  ============================================================
//
//  lab/ is the only source of the boss's brain. index.html carries a
//  generated copy between two marker lines, so the game still opens as one
//  file with no build step, and nothing is ever edited in two places:
//
//    node lab/inline.js          rewrite the blocks in index.html
//    node lab/inline.js --check  exit 1 if a block is out of date (tests use this)
//
//  Two blocks: the Neural Core (lab/core, below) and shared/ (sharedBlock).
//
//  What goes in: the modules the game runs (not the compressor, the lab, or
//  the tests), each wrapped so its require() finds the others, and the
//  connectome already built and compressed — building it in the browser
//  costs a stall D8 does not allow (see packGraph in connectome.js).

const fs = require('fs');
const path = require('path');
const { buildMockConnectome, packGraph } = require('./core/connectome.js');
const C = require('./core/compress.js');

const ROOT = path.resolve(__dirname, '..');
const INDEX = path.join(ROOT, 'index.html');
const BEGIN = '  // ==== NEURAL CORE — generated by lab/inline.js from lab/; edit there and re-run, never here ====';
const END = '  // ==== END NEURAL CORE ====';
const ANCHOR = '  // @@NEURAL_CORE@@';

//  The graph the boss thinks with. Changing these is changing its brain:
//  the Phase 2 bench chose 500 nodes, compressed from 2000, as the size that
//  discriminates situations and still costs well under a millisecond a tick.
const GRAPH = { nodes: 2000, seed: 0x5eed, keep: 500 };

const MODULES = [
  ['rng.js', 'core/rng.js'],
  ['connectome.js', 'core/connectome.js'],
  ['neural.js', 'core/neural.js'],
  ['worldstate.js', 'core/worldstate.js'],
  ['sensors.js', 'core/sensors.js'],
  ['fairness.js', 'core/fairness.js'],
  ['memory.js', 'core/memory.js'],
  ['player_model.js', 'core/player_model.js'],
  ['boss_body.js', 'core/boss_body.js'],
  ['tactics.js', 'core/tactics.js'],
  ['fsm_brain.js', 'core/fsm_brain.js'],
  ['game_adapter.js', 'adapter/game_adapter.js'],
  ['boss_runner.js', 'core/boss_runner.js'],
];

function theGraph() { return C.hybrid(buildMockConnectome({ nodes: GRAPH.nodes, seed: GRAPH.seed }), GRAPH.keep); }

function block() {
  const g = theGraph();
  const packed = packGraph(g);
  const parts = [BEGIN,
    '  //  ' + MODULES.map((m) => m[1]).join(', '),
    '  //  graph: mock connectome, ' + GRAPH.nodes + ' nodes compressed to ' + g.n + ' (' + g.m + ' edges), fingerprint ' + g.fingerprint(),
    '  const NC = (function () {',
    '    const defs = {'];
  for (const [name, rel] of MODULES) {
    const src = fs.readFileSync(path.join(__dirname, rel), 'utf8').replace(/\r\n/g, '\n');
    parts.push('      ' + JSON.stringify(name) + ': function (module, exports, require) {   // lab/' + rel);
    //  The commentary lives in lab/, where it is read; the copy drops lines
    //  that are only comments, and blank runs, which roughly halves it.
    //  Indented for reading — unless a line opens a template literal it does
    //  not close, where touching lines would change the string's contents.
    const lines = src.split('\n');
    const multiline = lines.some((l) => { const code = l.replace(/\/\/.*$/, '').replace(/'(?:[^'\\]|\\.)*'/g, ''); return (code.split('`').length - 1) % 2 === 1; });
    if (multiline) parts.push(src);
    else {
      const kept = [];
      for (const l of lines) {
        const t = l.trim();
        if (t.startsWith('//')) continue;
        if (!t && (!kept.length || !kept[kept.length - 1])) continue;
        kept.push(t ? '        ' + l : '');
      }
      parts.push(kept.join('\n'));
    }
    parts.push('      },');
  }
  parts.push('    };',
    '    const cache = {};',
    '    function req(name) {',
    "      name = name.replace(/^.*\\//, '');",
    '      if (cache[name]) return cache[name].exports;',
    '      const m = { exports: {} }; cache[name] = m;',
    '      defs[name](m, m.exports, req);',
    '      return m.exports;',
    '    }',
    '    return req;',
    '  })();',
    '  const NC_GRAPH = ' + JSON.stringify(packed) + ';',
    //  the readout trained in the lab (Phase 10), if there is one — the core
    //  refuses it unless it was trained on exactly this graph and seed
    '  const NC_READOUT = ' + readout() + ';',
    END);
  return parts.join('\n');
}

function readoutObj() {
  const f = path.join(__dirname, 'learn', 'readout.json');
  if (!fs.existsSync(f)) return null;
  const r = JSON.parse(fs.readFileSync(f, 'utf8'));
  return { v: r.v, graph: r.graph, seed: r.seed, w: r.w, b: r.b };
}
function readout() { const r = readoutObj(); return r ? JSON.stringify(r) : 'null'; }

//  The third output, a file of its own: what the room server's Beelzebub
//  thinks with (server/boss.js) — the same graph and readout as the Neural
//  Core block, as a core worked out in advance (NeuralCore.prepared()),
//  because building one there does not fit in a call's CPU time. Built the
//  way the game builds it (unpacked from the packed graph, the readout set
//  if it fits), so the two cores are one.
const BRAIN = path.join(ROOT, 'server', 'brain.js');
function brainFile() {
  const { NeuralCore } = require('./core/neural.js');
  const { unpackGraph } = require('./core/connectome.js');
  const core = new NeuralCore(unpackGraph(packGraph(theGraph())), { seed: 0xbeef });
  const ro = readoutObj(), trained = ro ? core.setReadout(ro) : false;
  return '//  GENERATED by lab/inline.js from lab/core — the room server\'s Beelzebub\n' +
    '//  core, worked out in advance (NeuralCore.prepared()). Never edit; re-run it.\n' +
    'export default ' + JSON.stringify({ trained, core: core.prepared() }) + ';\n';
}

//  The second block: shared/ — code the game and the room server both run
//  (the city's geometry, and later the rules). Inlined the same way, as its
//  own mini-require SH(name), placed before the city is built.
const SH_BEGIN = '  // ==== SHARED — generated by lab/inline.js from shared/; edit there and re-run, never here ====';
const SH_END = '  // ==== END SHARED ====';
const SH_ANCHOR = '  // @@SHARED@@';
const SHARED = [['city.js', '../shared/city.js'], ['rules.js', '../shared/rules.js'], ['items.js', '../shared/items.js'], ['troop.js', '../shared/troop.js'], ['traffic.js', '../shared/traffic.js'], ['wrecks.js', '../shared/wrecks.js'], ['dogs.js', '../shared/dogs.js'], ['gorgons.js', '../shared/gorgons.js'], ['flayers.js', '../shared/flayers.js']];

function sharedBlock() {
  const parts = [SH_BEGIN, '  //  ' + SHARED.map((m) => m[1].replace('../', '')).join(', '),
    '  const SH = (function () {', '    const defs = {'];
  for (const [name, rel] of SHARED) {
    const src = fs.readFileSync(path.join(__dirname, rel), 'utf8').replace(/\r\n/g, '\n');
    parts.push('      ' + JSON.stringify(name) + ': function (module, exports, require) {   // ' + rel.replace('../', ''));
    const kept = [];
    for (const l of src.split('\n')) {
      const t = l.trim();
      if (t.startsWith('//')) continue;
      if (!t && (!kept.length || !kept[kept.length - 1])) continue;
      kept.push(t ? '        ' + l : '');
    }
    parts.push(kept.join('\n'), '      },');
  }
  parts.push('    };', '    const cache = {};', '    function req(name) {',
    "      name = name.replace(/^.*\\//, '');",
    '      if (cache[name]) return cache[name].exports;',
    '      const m = { exports: {} }; cache[name] = m;', '      defs[name](m, m.exports, req);', '      return m.exports;',
    '    }', '    return req;', '  })();', SH_END);
  return parts.join('\n');
}

function current(html, begin, end) {
  begin = begin || BEGIN; end = end || END;
  const a = html.indexOf(begin), b = html.indexOf(end);
  if (a < 0 || b < 0) return null;
  return html.slice(a, b + end.length);
}

const BLOCKS = [
  { name: 'Neural Core', begin: BEGIN, end: END, anchor: ANCHOR, make: block },
  { name: 'Shared', begin: SH_BEGIN, end: SH_END, anchor: SH_ANCHOR, make: sharedBlock },
];

if (require.main === module) {
  let html = fs.readFileSync(INDEX, 'utf8');
  const check = process.argv.includes('--check');
  let stale = 0, wrote = 0;
  for (const B of BLOCKS) {
    const want = B.make(), have = current(html, B.begin, B.end);
    if (have === want) continue;
    if (check) { console.error('lab/inline.js: the ' + B.name + ' block in index.html is ' + (have ? 'out of date' : 'missing') + ' — run node lab/inline.js'); stale++; continue; }
    // a function, so a '$' anywhere in the code is never read as a replacement pattern
    if (have !== null) html = html.replace(have, () => want);
    else if (html.includes(B.anchor)) html = html.replace(B.anchor, () => want);
    else { console.error('lab/inline.js: no ' + B.name + ' block and no ' + B.anchor.trim() + ' anchor in index.html'); process.exit(1); }
    wrote += want.length;
  }
  const brain = brainFile(), brainHave = fs.existsSync(BRAIN) ? fs.readFileSync(BRAIN, 'utf8') : null;
  if (check) {
    if (brain !== brainHave) { console.error('lab/inline.js: server/brain.js is ' + (brainHave ? 'out of date' : 'missing') + ' — run node lab/inline.js'); stale++; }
    if (stale) process.exit(1);
    console.log('lab/inline.js: index.html and server/brain.js are up to date'); process.exit(0);
  }
  fs.writeFileSync(INDEX, html);
  if (brain !== brainHave) fs.writeFileSync(BRAIN, brain);
  console.log('lab/inline.js: ' + (wrote ? 'wrote ' + (wrote / 1024).toFixed(0) + ' KB into index.html' : 'index.html was already up to date') +
    (brain !== brainHave ? '; wrote server/brain.js (' + (brain.length / 1024).toFixed(0) + ' KB)' : ''));
}

module.exports = { block, sharedBlock, current, BEGIN, END, ANCHOR, SH_BEGIN, SH_END, SH_ANCHOR };
